#!/usr/bin/php
<?php
require __DIR__ . '/vendor/autoload.php';
require __DIR__.'/lib/class.BitstampNet.php';
require __DIR__.'/lib/debug.php';
require __DIR__.'/lib/bitstamp-cli-utilities.php';

$localConfig = array();
if (file_exists(__DIR__.'/config-local.php')) {
    require __DIR__.'/config-local.php';
}

if ($argc === 1) {
    printUsage();
    exit(0);
}
$action = $argv[1];

$cli = new Mx17\BitstampPHP\BitstampNet($localConfig);
$cli->setCurrency('btceur');

switch ($action) {
    case 'ticker':
        $data = $cli->ticker();
        printTable(array($data));
        break;
    case 'tickerHour':
        $data = $cli->tickerHour();
        printTable(array($data));
        break;
    case 'orderBook':
        $data = $cli->orderBook();
        echo print_r($data, 1)."\n";
        break;
    case 'transactions':
        $data = $cli->transactions();
        printTable($data);
        break;
    default:
        echon(basename(__FILE__).": unrecognized argument");
        exit(1);
        break;
}

//echo "== Transactions\n";
//$data = $cli->transactions();
//printTable($data);

//$data = $cli->conversionRate();
//echo "conversionRate: ".print_r($data, 1)."\n";

//$data = $cli->balance();
//echo "balance: ".print_r($data, 1)."\n";

//echo "== All open orders\n";
//$data = $cli->openOrders();
//printTable($data);

//echo "== User transactions\n";
//$data = $cli->userTransactions(0, 10, 'desc');
//printTable($data);

//echo "== Open new order\n";
//$data = $cli->buy(1, 25);
//echo print_r($data, 1)."\n";
//$orderId = $data['id'];
//
//echo "== Open new order\n";
//$data = $cli->buy(1, 25.5, 9000);
//echo print_r($data, 1)."\n";
//$orderId = $data['id'];

//echo "== Order status $orderId\n";
//$data = $cli->orderStatus($orderId);
//echo print_r($data, 1)."\n";

//echo "== All open orders\n";
//$data = $cli->openOrders();
//printTable($data);

//$data = $cli->cancelOrder($orderId);
//echo print_r($data, 1)."\n";

//echo "== Cancel all orders\n";
//$data = $cli->cancelAllOrders();
//echo print_r($data, 1)."\n";

//echo "== All open orders\n";
//$data = $cli->openOrders();
//printTable($data);


// vim: syntax=php
